// 1- Primero se crea una funcion , en este caso que genere un elemento:
// 2- function generarElemento()
function generarElemento() {
// 3- Se crea una varible = array, que contenga todos los elementos dentro.
   var elementos = ["¿Cuál es tu posición favorita?",
   "¿Cuál ha sido el mayor número de veces seguidas que lo has hecho?","¿Qué te gusta que hagan para excitarte?",
   "¿Te has tocado en el mismo cuarto que otras personas cuando todos están dormidos?",
   "¿Alguna vez has pensado en alguien más mientras estás haciendo el amor?",
   "¿Alguna vez fantaseaste conmigo?","¿Lo has hecho estando en una alberca o en el mar?",
   "¿has fantaseado con un(a) profesor/a?","¿Qué es lo más fuerte que has dicho o gritado en el calor del momento?",
   "¿Cuánto tiempo te tardas en promedio para terminar?","¿Cuándo fue la última vez que te tocaste y en quién estabas pensando?",
   "¿Alguna vez lo has hecho mientras otra u otras personas te veían?","¿Qué edad tenías cuando perdiste tu virginidad?",
   "Menciona el lugar más inadecuado en el que lo hayas hecho.","Menciona la persona más extraña con quien te has imaginado teniendo relaciones.",
   "¿Con qué persona de la televisión o del cine lo harías sin pensártelo dos veces?","¿Cuál ha sido el mayor tiempo que has durado haciéndolo?",
   "¿Alguna vez has dicho el nombre de otra persona mientras tenías relaciones?","¿Alguna vez se te ha roto el preservativo en medio del acto?",
   "Menciona algún tipo de video para adultos que hayas visto y te haya perturbado.","¿Qué términos usas más frecuentemente para buscar videos eróticos en línea?",
   "¿Alguna vez has visto a alguien hacerlo o tocarse sin que la persona supiera?","¿Cuántas parejas íntimas has tenido en un día?",
   "¿Qué es lo más extremo que has hecho tras una calentura y con nadie disponible para calmar tus ansias?","¿Cómo fue tu primera vez?",
   "¿Con cuántos contactos de los que tienes en tu teléfono has tenido algún tipo de contacto íntimo?","¿Has tenido relaciones en un automóvil?",
   "¿Alguna vez has jugado al póker erótico?","¿Qué tan frecuentemente te masturbas?","¿Cuál es la fantasía que más quieres hacer?",
   "¿Lo harías en la primera cita?","¿Cuál ha sido el último sueño erótico que has tenido?","¿Replicarías una escena de una película porno?",
   "¿Te gustaría someter a tu pareja o ser sometido?","¿Prefieres que esté depilado/a o completamente al natural?",
   "¿cuál sería el lugar más inapropiado en el que te gustaría hacerlo?","¿Qué es irresistible para ti en el cuerpo de una pareja?",
   "¿Qué consideras que es lo más extraño que te pone?","¿Qué consideras que es lo más extraño que te pone?","¿Te has acostado con más de una persona el mismo día?",
   "¿Qué opinas que es lo mejor que tu pareja podría hacer en la cama para complacerte?","¿Qué es aquello que consideras que no podrías hacer en la cama?",
   "¿Consideras que las relaciones deben de ser lindas y románticas o rudas y apasionadas?","¿Cuál es la frecuencia que consideras ideal para intimar con tu pareja?",
   "¿Qué tanta experiencia consideras que tienes en la cama?","¿Eres partidario de la idea de que hay que esperarse a tener relaciones solo con alguien que ames?",
   "¿Alguna vez has fantaseado que alguien juega a forzarte?","¿Alguna vez has considerado tener o has tenido relaciones abiertas?",
   "¿Alguna vez has visto a otra pareja hacerlo sin que ellos lo supieran?","¿Alguna vez te han hecho un estriptís?","¿Te has acostado con alguien mucho más mayor que tú? ¿Cómo te sentiste?",
   "¿Alguna vez has tenido un amigo/a sexual?","¿Alguna vez has hecho juego de roles?","¿Cuál es el juguete más loco que has usado o te gustaría utilizar?",
   "¿Qué piensas acerca de hacer el amor en medio de la lluvia?","¿Crees que los preliminares son importantes, o te gusta ir directo al grano cuando se trata de la intimidad?",
   "¿Qué opinas de la idea de utilizar juguetes en la intimidad?","¿Arriba o abajo?","¿Saldrías con varias personas simultáneamente?",
   "¿Dónde es el lugar más arriesgado donde has tenido un encuentro íntimo?","¿Más sexo significa más felicidad en una relación?",
   "¿Te gusta desnudarte delante de tu pareja, independientemente del estado de tu cuerpo?","¿Has recurrido al hielo para hacer más intensa la experiencia sexual?",
   "¿Le harías un striptease a tu pareja?","¿Alguna vez has preparado un baño sensual para ti y tu pareja?","¿Has fingido alguna vez un orgasmo?",
   "¿Harías un trío con tu pareja y un amigo/a?","¿Qué posición disfrutas menos cuando tienes relaciones sexuales?",
   "¿Alguna vez has tenido relaciones sexuales mientras otras personas te miran?","¿Qué es lo que más te causa placer?","¿Alguna vez has pillado a alguien en medio de una relación sexual?",
   "¿Alguna vez has tenido relaciones sexuales con más de una persona al mismo tiempo?","¿Te gusta experimentar en la cama?",
   "¿Te gusta tomar la iniciativa?","¿Alguna vez has seducido a una persona desconocida?","¿Cuál es el juguete sexual más extraño que has usado?",
   "¿Cuál es la máxima cantidad de orgasmos que has tenido en un encuentro sexual?","¿Cuál es la propuesta más indecente que te han hecho?",
   "¿Qué posición disfrutas más cuando tienes relaciones sexuales?","¿Qué recuerdas de tu mejor experiencia sexual?","¿Has fantaseado alguna vez con la pareja de tu mejor amigo/a?",
   "¿Has tenido una experiencia sexual con alguien menor que tú?","¿Cuál ha sido la ropa interior más atrevida que has usado?","¿Te gusta usar ropa interior atrevida?",
   "¿Has tenido alguna experiencia sexual con alguien mayor que tú?","¿Cuál es la propuesta más indecente que has hecho?","¿Parado o acostado?",
   "¿Alguna vez has tenido relaciones sexuales en un sitio público?","¿Has cumplido alguna vez una fantasía sexual?","¿Cuál es el máximo tiempo que has estado sin relaciones sexuales?",
   "¿Has besado a alguien que tenga el doble de tu edad?","¿Alguna vez has mentido para acostarte con alguien?","¿Has besado a alguno de tus amigos más cercanos? ¿Quién?",
   "¿Qué es lo más vergonzoso que te ha sucedido estando desnudo?","¿Alguna vez has mentido a tu pareja para evitar un momento íntimo, por ejemplo, decir que te duele la cabeza?",
   "¿Cuál crees que es la parte más atractiva de tu cuerpo?","¿De qué color es tu ropa interior?","¿Quién es la persona que más quieres besar?",
   "¿Cuál es tu placer prohibido?","Si una persona a la que estás conociendo te confiesa ser bisexual, ¿te parecería atractivo o más bien al contrario?",
   "¿Has tenido relaciones estando muy ebrio alguna vez?","¿Tienes algún primo o prima con el que no te importaría tener una relación?","¿Qué es lo más loco que has hecho para intentar gustar a alguien?",
   "¿Qué cualidad física te hace caer rendido/a a los pies de alguien?","¿Has tenido conversaciones subidas de tono por chat o WhatsApp?",
   "¿Hay algún uniforme que te excite especialmente?","Imagina que tienes el superpoder, durante una noche, de meter en tu cama a quien tú quieras. ¿Quién sería?",
   "¿Cuál es tu sitio favorito para tener relaciones?","¿Has entrado alguna vez a un cuarto oscuro?","¿Alguna vez te has enrollado con varias personas en una misma noche?",
   "¿Te gusta practicar las relaciones íntimas en lugares poco habituales?","Si ves accidentalmente una una persona del sexo opuesto desnuda y no lo sabe, ¿seguirías mirando?",
   "¿Qué es lo que más te excita?","¿Cómo fue tu primera experiencia sexual?","¿Cómo te sentirías si pillas a tu pareja dándose autoplacer?",
   "¿Has fingido alguna vez un orgasmo?","¿Has fingido alguna vez un orgasmo?","¿Algunas vez has hecho o has propuesto hacer un trío?",
   "¿Has participado en alguna orgía?","¿Te han pillado masturbándote alguna vez?","¿Has usado alguna vez algún juguete erótico?","¿Cuánto es lo mínimo que ha durado un encuentro sexual con alguien?",
   "¿Te gustó tu primera vez, o fue un desastre?","¿Cuánto porno ves a la semana?","Alguna vez has tenido sexo en público?, ¿dónde?",
   "¿Con cuántas personas te has acostado en tu vida?","¿Tienes algún fetiche que no le hayas contado a nadie?","¿Alguna vez duermes desnudo?",""];
// 4- se crea una funcion de arroje un elemento aleatorio dentro de ese array.
   var indiceAleatorio = Math.floor(Math.random() * elementos.length);
// 5.1- El elemento *Math.floor(Math.random()* genera un elemento aleatorio y se multiplica por la variable + "".length"
   document.getElementById("resultado").value = elementos[indiceAleatorio];
// 6- se crea un "document.getElementById("ID").value = elementos[indiceAleatorio];" para que este imprima el elemento dentro del input
 }
